print("welcome to COM411")
print("In week 1 we will learn...")

print("...How to use Git and GitHub")
print("...How to out to the screen")
print("...How to get user input")

print("I hope you are enjoying the lesson thus far!")

print("What is your name?")
name = input()
print(f"Its nice to meet you {name}")

print("please enter a character for the eye")
eye = input()

print(f"please enter an {eye}")

print("##########")
print(f"#  {eye}  {eye}  #")
print("#  ----  #")
print("##########")

print("What is your name?")

name = input()

print("How old are you(In years)?")

years = int(input())

print("How tall are you (In meters)?")

meters = float(input())

print("how much do you way(In kilograms)?")

kilograms = int(input())

bmi = kilograms/meters**2

print(f"{name} you are {years} old and your bmi is {bmi:.2f}")

print("Please enter number of lives")

lives = int(input())

print("enter energy level")

energy = int(input())

print("please enter shield")

shield = int(input())

print(f"{'♥'*'lives'}")
print("♥"*5)




